// Copyright 2026 YAS Softwares LTDA
// SPDX-License-Identifier: Apache-2.0

// Generated by `shadcn init`. Every generated component imports `cn` from here.

import { clsx, type ClassValue } from 'clsx';
import { twMerge } from 'tailwind-merge';

export function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs));
}
